### ISSUE TITLE
期待你的开源做的更好~

### ISSUE THREAD

**Issue by Geek-James** [zuihou/zuihou-ui#1]
一枚前端,有自己的服务器,有自己的开源项目,后续有时间可以和你合作完善下你这项目~

**Comment by zuihou** [comment]
> 一枚前端,有自己的服务器,有自己的开源项目,后续有时间可以和你合作完善下你这项目~

加QQ群：63202894， 备注github账号或者私聊群主，期待你的加入。
本人后端一枚，大部分精力也在搞后端项目（zuihou-admin-cloud)，前端方面只能勉强编码，期待你加入，一起完善或者优化这个前端项目。
