### ISSUE TITLE
修改密码form校验器行为异常

### ISSUE THREAD

**Issue by pinkcao** [zuihou/zuihou-ui#16]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

在官网当前已经部署的任意版本中
个人中心→安全设置→修改密码
该form控件中从后端获得的校验规则会使其校验行为异常，校验的反馈为上一次行为的结果

bug如图
![image](https://github.com/zuihou/lamp-web/assets/36530450/c0e6e485-fbe8-45d1-9217-ade7b857275d)
本条应该是在未输入的情况下得到的校验结果

![image](https://github.com/zuihou/lamp-web/assets/36530450/5773cd23-9290-4a9b-b33a-63a69a6f2b64)
本条应该是校验通过

![image](https://github.com/zuihou/lamp-web/assets/36530450/880c9668-e47e-40d2-81cc-6c82546f8a27)
本条是在上一条删除一个字符后得到的校验结果，为通过状态

### 复现 Bug

打开官网任意版本的前端，进入个人中心→安全设置→修改密码，输入5672a_，可见校验不通过，删除_后可见校验通过

## 系统信息

- 操作系统: 任意
- Node 版本: 任意
- 包管理器 (npm/yarn/pnpm) 及其版本: 任意

**Comment by pinkcao** [comment]
在StrengthMeter.vue组件中修改一下
![image](https://github.com/zuihou/lamp-web/assets/36530450/2964eb87-103e-4012-b1c8-b900eb83384f)
在handlechange时同时emit change事件即可

**Comment by zuihou** [comment]
👍🏻
