### ISSUE TITLE
菜单资源授权bug,对指定菜单资源授权会覆盖其他菜单授权

### ISSUE THREAD

**Issue by billForgithub** [zuihou/zuihou-ui#3]
![image](https://user-images.githubusercontent.com/3689481/72510199-f590cc00-3883-11ea-937a-39551709b643.png)
![image](https://user-images.githubusercontent.com/3689481/72510210-f9245300-3883-11ea-9f21-5e00a4cc91c1.png)
![image](https://user-images.githubusercontent.com/3689481/72510219-fe819d80-3883-11ea-857f-99c78f8b1483.png)

**Comment by zuihou** [comment]
已解决
