### ISSUE TITLE
pnpm install 安装一直失败 好难受 求大佬指点一下 

### ISSUE THREAD

**Issue by zsl1549** [zuihou/zuihou-ui#7]
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/32888522/202887085-55f58ceb-01b4-4526-9263-7f06eceb54f2.png">
node v16.18.0
npm 8.19.2
pnpm 7.16.1

**Comment by zuihou** [comment]
https://www.kancloud.cn/zuihou/zuihou-admin-cloud/2405117


```
# 安装依赖
npm install --registry=https://registry.npm.taobao.org

如果还报错， 请保持访问国外网络通畅，以及逐个试试下面的方法：

npm i node-sass --sass_binary_site=https://npm.taobao.org/mirrors/node-sass/

git config --global url."https://".insteadOf git://

npm install chromedriver --chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver

cnpm install core-js@2.6.9 

# 还不行？学会搜索吧...  我也不知道如何解决。

```

**Comment by zsl1549** [comment]
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/32888522/202888077-baa683ba-49d4-41d8-9810-67513ab19425.png">
@zuihou  大佬帮忙看看什么问题
