### ISSUE TITLE
启动项目一直报错 ant-vue 找不到

### ISSUE THREAD

**Issue by zsl1549** [zuihou/zuihou-ui#8]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/32888522/202893126-863e213a-8911-41fc-bbca-04d599184337.png">
"ant-design-vue": "3.2.0"

**Comment by zsl1549** [comment]
@zuihou 大佬帮忙看看

**Comment by zsl1549** [comment]
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/32888522/202894209-fb0edfe8-8fb9-47bd-ba0a-d67f862f3f1d.png">

**Comment by zuihou** [comment]
通过官方渠道获取最新的、正确的 lamp 的源码, 并保持网络畅通
删除： pnpm-lock.yaml  和 node_modules 

执行 
```
pnpm install --registry=https://registry.npmmirror.com

# 确保install 没有报错后，在运行
pnpm serve
```
