### ISSUE TITLE
关于M1芯片下npm install相关问题

### ISSUE THREAD

**Issue by WZR8277** [zuihou/zuihou-ui#9]
MacOS系统的M1芯片应该使用npm install --ignore-scrips，然后卸载node-sass换为sass，这个install的过程确实很长（我自己挂了梯子 register用的默认而不是淘宝）

**Comment by zuihou** [comment]
可以用淘宝源试试速度

**Comment by zuihou** [comment]
已更新文档，感谢提供的解决方案

**Comment by zuihou** [comment]
已按照你说的修改代码，麻烦有空帮看看

**Comment by WZR8277** [comment]
看见文档内容更新了。但是之前按照我的尝试，我这边淘宝镜像源不能解决m1 install缓慢的问题。另外更新的代码解决了/deep/语法报错，但是无法解决编译报错，依然还是要先操作npm uninstall node-sass和npm install  --save-dev sass（参考https://stackoverflow.com/questions/68095626/node-sass-with-apple-m1-big-sur-and-arm64）。
